version: '3'
services:
  jenkins:
    container_name: jenkins-master
    image: 'davis8988/jenkins-master:configured-2.194-lts'
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      - "ARTIFACTORY_SERVER_ID=hello world"
      - "DOCKER_CLOUD_NAME=hell its about time"