# This dockerfile configures jenkins master image
FROM jenkins/jenkins:2.222.4-lts

LABEL Description="This image is for running jenkins master server as a container"
LABEL maintainer="yair.david@elbitsystems.com"

# Copy apt-get sources:
COPY apt/ /etc/apt


