# This dockerfile configures jenkins master image
FROM nteptartifact:5014/jenkins:latest

LABEL Description="This image is for running jenkins master server as a container"
LABEL maintainer="yair.david@elbitsystems.com"

# Copy apt-get sources:
COPY apt_sources/v18.04_bionic/ /etc/apt


